version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: coffee_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffee_db
    ports:
      - "5432:5432"
    volumes:
      - coffee_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  coffee_data:
